import Head from "next/head";
import { Inter } from "next/font/google";
import { Typography, Box } from "@mui/material";
import { SxProps, ThemeOptions } from "@mui/system";

const inter = Inter({ subsets: ["latin"] });

import useWindowDimensions from "@/hooks/useWindowDimensions";
import HomePage from "@/components/homePage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: 0 }}>
        {/* <main> */}
        <HomePage />
      </main>
    </>
  );
}
